version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "python /code/manage.py runserver 0.0.0.0:8000"
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery
  celery:
    build: .
    command: celery -A payment worker -l info
    volumes:
      - .:/code
    depends_on:
      - redis